### ISSUE TITLE
My Wrye Bash/Smash/Flash involvement

### ISSUE THREAD

**Issue by Sharlikran** [Sharlikran/wrye-bash#19]
I'm sorry for making a pull request and then removing the branch from my repo but I think there is a misunderstanding about my involvement with the project.  I do what I like, how I like, and when I like on my fork.  Simple as that.

When you read this @Utumno if you don't like the comment don't tell me that you don't appreciate comments like this because you came to me with a question, not the other way around.  So I will say what I like.

Again I wish you luck and good fortune with your life and this project.  I wish you no ill will.  I am done working on this project except on my fork.  I appreciate the work you are doing and I hope it continues.

I have also somehow been unclear so I'll clarify.

If after you read this you become upset and you plan to or decide to remove the LOOT API and the ability for Wrye to import the Bash tags from the three LOOT sources we have discussed I will contact @lojack5 every day unless I get tired of doing so or don't have time until he responds and ask him to tell you to put it back.  That is of course unless he deletes his e-mail address or blocks me or turns off GitHub notifications.

Not using the LOOT code changes I made is simply stupid.  Everyone is or will be updating to the current LOOT 0.9.0 and by not using the new DLL will mean they will report a bug with Wrye like was reported in the Beth forums.  You keep missing the point about the simple fact that you need the new dll I provided.  I don't care about what you like or don't like or whether or not this or that pollutes the repo.  Users don't care about the logistics of things or how you maintain the Git repo.  They simply want Wrye to work correctly and to KEEP THE PREVIOUSLY EXISTING FUNCTIONALITY!  Users don't like things removed or features they use to go away.

If you think for one second that users are going to give you exemplary bug reports formatted the way you want you are living in a dream world.  It is also rude to tell a user that you will not troubleshoot their package or installer issues.  In the last instance it was a bug you introduced and wouldn't have found if I had not reported it, and probably wouldn't have looked into it unless about 3 or 4 other people came along and said something about it.

I have even had another traceback but I'm not going to tell you because if I do it won't be to your perfect reporting standards.  So I'll wait for some other user to report it and it won't be how you like it but you can tell them about your bug reporting standards and they can tell you that they don't care.

Users don't know Python or understand the traeback.  Look at this users report for [Wrye Flash for Fallout New Vegas](https://forums.nexusmods.com/index.php?/topic/250367-wrye-flash-nv/?p=37580990), which I am going to fix today.  Do you think that user gives a crap about anything except the fact that Wrye Flash isn't working?  Users don't care about anything but that Wrye works they way it has and the way they want.

If you remove too many things, especially for Oblivion, people will simply stick with 292.x like they always have and won't even bother with trying out 307.  If you want to know what users think go to the Oblivion nexus and talk to them about it.  Users on the Oblivion Nexus probably think the project is dead anyway.  You may not get responses very quickly because they have given up asking since probably nobody from the project ever responds to questions.  If they don't see activity they will go elsewhere. If they go elsewhere and don't see what they want they may not even ask.

I'll bet you users ask themselves which is the best version to use.  I'll bet you they don't say anything about 300+ and especially not 306.  They will probably say that 292-295ish are the best versions to use.  Don't ask me why they think that or what they think.  They have been reporting what they don't like in the Bethesda forums or on the Nexus and it's been ignored.  Go read their comments, or ask them yourself because I DON'T KNOW!   Ask them if they want this or that removed or what features they think are broken.

You say what about XP support for LOOT when I don't even know if Wrye Bash has XP support.  It doesn't make a w9xpopen.exe for 307 as far as I know.  I don't even know what w9xpopen.exe is because i don't write code for Wrye and I don't know Python.  I'm not the person you should even be asking.  I just added the Skryim definitions however many years ago, two years I think or at least one and a half years.  Don't ask me questions about XP support for LOOT, go read WrinklyNinja's documentation or [better yet his change logs](https://github.com/loot/loot/releases).  Do not ask me about BOSS support and when it stopped supporting XP, go read WrinklyNinja's documentation or [the BOSS change logs](https://github.com/boss-developers/boss/releases).  Don't ask me the differences about LOOT and BOSS again, because i already explained that.  Do not ask me if any if my code is or isn't safe or stable.  Do not ask me to rebase my changes so you can cherry pick commits.  Don't ask me to update any WIKI pages or any of Wrye's documentation.  The code is under a GPL use whatever you like but don't ask me about it.

When you go to make Wrye Flash patch leveled lists for Fallout 4 don't ask me to port the FO4Edit code to Wrye Flash.  Don't ask me where the FO4Edit code is located or what it means.  Do not make any demands or requests for documentation of what the xEdit code does in the xEdit issue tracker, I will delete it.  I will probably port the code for my own personal use and when I do if you want to use the code that's fine, it's under a GPL.

**Comment by Sharlikran** [comment]
You know, I forgot something.  I probably can't update to the LOOT 0.9.0 API because the proper changes have not been made to loot.py for the 0.9.0 API.

**Comment by Utumno** [comment]
> you plan to or decide to remove the LOOT API 

Once and for all: I am not an idiot. I did hope that this at least was clear.

Since it is not - of course I will not be removing such essential functionality. You have been saying this to me and I kept ignoring it as I would ignore someone who was worrying I would remove BAIN from bash. Bullshit

I was not ignoring _you_ however cause you are not to be ignored - neither your comments, nor your tracebacks.

>  I do what I like, how I like, and when I like on my fork. Simple as that.

No, its even simpler than that. Only an idiot would dispute that - see above.

So if you stop considering me an idiot and concentrate on what _I do_ say maybe the binding of LOOT with Bash will be soon solved. And maybe your fork will be a tad more useful to you, and to me.

I have no more energy to spend on misunderstandings - I am dry and technical (and not an idiot). Do as I say, ask me when in doubt and keep working for bash, as I do ;)

-----

>  I probably can't update to the LOOT 0.9.0 API because the proper changes have not been made to loot.py for the 0.9.0 API.

You do not mean of course that your pull request (which is on my local tree already) won't start ?

**Comment by Utumno** [comment]
Seriously now Sharl - we are civilized people and not 14 years old like our users. If you really don't want to work on Bash anymore that's fine, if you do here is a solution to your fork issue (it is an issue cause to keep it in sync, which is obviously needed, you need to rebase and obviously again you may not be able to solve conflicts due to my changes):

- give me write rights
- I push _only_ to a feature-sharlikran-valda-fallout-on-dev branch
- whenever you feel like it (but the sooner the better) you compare your branch to this one and you rebase

A bit more work for me but i can afford.

So this one is solved

Re: loot- in my mind and (I am not an idiot) must be in for beta. In the worst case I could merge your pull - but is worst case. Then try and solve that one for good. The points on the repo and maintenability when I raise you just have to respect - I do obviously realize the users are not concerned but as the one who put Bash up on its feet I do know my onions and binding of loot and Bash _is_ problematic. My arguments are not there to convince you - I could write volumes, but I simply thought you knew I knew what I was talking about. And writing volumes (even those volumes here now) takes time and _energy_. Today I was off work and wanted to finalize my wip stuff (so then I could look at loot and patchers). This has costed me immense energy. Next time I can really work is Saturday. So whether you stay or go - please from now on let's get dry and technical :)

**Comment by Sharlikran** [comment]
Before you keep reading.  I know your time is limited so really don't spend time reading this or responding when you have other things to do.  Return to this another day when you have time or over the weekend or whatever.

> Do as I say

How would WrinklyNinja respond to that?  How did he respond to your request when you wanted to push your lobloadorder32.dll changes to his upstream?  Is he part of the Wrye Bash organization, am I?

> ask me when in doubt and keep working for bash, as I do ;)

I really like this project and I'd like to see it continue being worked on.  I may not however be able to ask you questions in the future.  I am currently undecided.

> Once and for all: I am not an idiot.

I don't think you are an idiot.  I'm tired of fighting with you and I'm tired of being told certain things.  So I left the project.  You seem to keep thinking that after enough time passes that I will just keep working on things as if nothing has ever happened.  I can see that trying to provide code or help isn't going to be possible without all the same stuff happening that I don't like.  

I have made my decision.  I'm only going to do what I feel like doing from now on, and that's it.  That may or may not ever change.

I know that you know what you are doing and you have 12 years or more experience doing it.  I get that.  I can't program in Python.  I look up to you and greatly respect you when it comes to Python programming or Git related knowledge.  Your guidance with Git was appreciated.  In fact I recently used git reflog to revert my Rebase on Rc2 when you introduced that bug so I could return to using Rc1.  I could not have done such an advanced operation without your help.

> You do not mean of course that your pull request (which is on my local tree already) won't start ?
> loot- in my mind ... must be in for beta

Then any further talk about it would be superfluous, you know what has to happen and probably decided to do this already.

- You can't keep the current DLL because it's outdated.
- You can't upgrade to the DLL in commit 16eda5bd93c9f9eb12c3de1bff70f270465a69c5 because there is no Fallout 4 support.  There are two changes in loot.py in that commit that you will need for 0.9.0.  I made those changes with code from WrinklyNinja.  I don't know what other changes are required.

So it's clear that when you have time over the next few weeks or whatever you have planned, you will need to download the latest [LOOT API 0.9.0 g44a0d85](https://github.com/loot/loot/releases) update loot.py.  Then test it with Oblivion to make sure there are no anomalous Bash Tags.

**Comment by Utumno** [comment]
Thanks for pointers for LOOT. Hiding tracebacks is a crime in the software world where benevolent dictators live: https://www.google.be/search?hl=en&q=torvalds+benevolent&gws_rd=cr,ssl&ei=uuVFV5TPKsX5aq6hivAE
